---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ home_path }}"
    copy: no

- name: Move wordpress files into webroot
  command: "mv -v {{ home_path }}/wordpress {{ webroot }}"


- name: Copy sample config file
  command: "mv {{ webroot }}/wp-config-sample.php {{ webroot }}/wp-config.php"
  args:
    creates: "{{ webroot }}/wp-config.php"
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest: "{{ webroot }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ database_name }}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ database_username }}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ database_user_password }}');"}

- name: make log dir
  file:
    path: "{{ webroot }}/wp-content/uploads"
    state: directory

- name: upload wp-contents
  synchronize:
    src: uploads/
    dest: "{{ webroot }}/wp-content/uploads"
